### ISSUE TITLE
Error from npm start

### ISSUE THREAD

**Issue by lukephills** [markogresak/typescript-react-jsx-example#1]
Hi when i run `npm start` i get this error:

ERROR in ./index.tsx
Module build failed: TypeError: undefined is not a function
    at ensureTypeScriptInstance (/Users/luke/Sites/typescript-react-jsx-example/node_modules/ts-loader/index.js:147:38)
    at Object.loader (/Users/luke/Sites/typescript-react-jsx-example/node_modules/ts-loader/index.js:365:14)

**Comment by markogresak** [comment]
Hi, I'll take a look at it. The problem is that this project is a bit old if you consider how actively React api is changing.

**Comment by markogresak** [comment]
I was assuming wrongly about React, but it's updates did break some of my older projects.

Apparently all I had to do is update dependencies and it works. Adding an update to prevent this in the future.

**Comment by lukephills** [comment]
Thank you for fixing this! For reference, my version of node needed updating and I updated ts-loader to v0.7.2

Nice blog too!

**Comment by markogresak** [comment]
@lukephills thanks, I'm glad it helped you.
